export const PRODUCTS_FETCH_REQUEST = 'PRODUCTS_FETCH_REQUEST';
export const PRODUCTS_FETCH_REQUEST_SUCCESS = 'PRODUCTS_FETCH_REQUEST_SUCCESS';
export const PRODUCTS_FETCH_REQUEST_FAILURE = 'PRODUCTS_FETCH_REQUEST_FAILURE';