export const PRODUCTS_FETCH_REQUEST = 'PRODUCTS_FETCH_REQUEST';
export const PRODUCTS_FETCH_REQUEST_SUCCESS = 'PRODUCTS_FETCH_REQUEST_SUCCESS';
export const PRODUCTS_FETCH_REQUEST_FAILURE = 'PRODUCTS_FETCH_REQUEST_FAILURE';

export const SELECTED_PRODUCTS_FETCH_REQUEST = 'SELECTED_PRODUCTS_FETCH_REQUEST';
export const SELECTED_PRODUCTS_FETCH_REQUEST_SUCCESS = 'SELECTED_PRODUCTS_FETCH_REQUEST_SUCCESS';
export const SELECTED_PRODUCTS_FETCH_REQUEST_FAILURE = 'SELECTED_PRODUCTS_FETCH_REQUEST_FAILURE';